name: Publish Check CI results

# WARNING:
# workflow_run provides read-write repo token and access to secrets.
# Do *not* merge changes to this file without the proper review.
# We should only be running trusted code here.
on:
  workflow_run:
    workflows: [ "Test Result CI" ]
    types:
      - completed

jobs:
  # Job based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  publish-check-ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Unfortunately, the official actions/download-artifact action is very limited in scope.
      # Can't use it yet in this context, https://github.com/actions/download-artifact/issues/60
      - name: Download artifact
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # 8.0.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "check-ci-results"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/check-ci-results.zip', Buffer.from(download.data));
      - run: unzip check-ci-results.zip
      - name: Publish Test Results
        uses: scacap/action-surefire-report@5609ce4db72c09db044803b344a8968fd1f315da # 1.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
