name: reviewdog
on: [ pull_request ]
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@26c5e9b625966139d9956cbbb6217375480d4e14 # 0.19.0
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
          reporter: github-pr-review
