name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # "weekly" https://crontab.guru/every-week
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - name: Set up JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # 5.5.0
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # 2.1.0
        with:
          repo-token: ${{ secrets.GH_ACTION_TOKEN }}
          labels: dependencies
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # 6.2.0
