name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # "weekly" https://crontab.guru/every-week
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # 5.7.0
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # 2.1.0
        with:
          repo-token: ${{ secrets.GH_ACTION_TOKEN }}
          labels: dependencies
      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # 6.3.0
