name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # "weekly" https://crontab.guru/every-week
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # 5.6.0
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # 2.1.0
        with:
          repo-token: ${{ secrets.GH_ACTION_TOKEN }}
          labels: dependencies
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # 6.2.0
